services:
#  bot:
#    build: .
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - ./data/bot_supervisor_logs:/var/log/supervisor
#    networks:
#      - db_network
#      - minio_network
#      - redis_network

  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=2000'
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=survey
      - POSTGRES_DB=survey
    networks:
      - db_network

  pgbouncer:
    image: edoburu/pgbouncer
    restart: always
#    platform: linux/amd64   # mac m1
    environment:
      - DB_USER=survey
      - DB_PASSWORD=example
      - DB_HOST=postgres
      - DB_NAME=survey
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,survey
      - MAX_CLIENT_CONN=2000
      - DEFAULT_POOL_SIZE=100
      - AUTH_TYPE=plain
    depends_on:
      - postgres
    networks:
      - db_network
    ports:
      - "5434:5432"

  minio:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: server /data
    volumes:
      - ./data/minio_data:/data
    networks:
      - minio_network
    ports:
      - 9000:9000

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - ./data/redis:/data
    networks:
      - redis_network
    ports:
      - "6380:6379"

networks:
  db_network:
    driver: bridge
  minio_network:
    driver: bridge
  redis_network:
    driver: bridge
